In [ ]:
!pip install alpha_vantage

import pandas as pd
import matplotlib.pyplot as plt
from alpha_vantage.timeseries import TimeSeries
import requests
from time import sleep

In [ ]:
# api_key_1 = 'KA4LIC1TXIS8RKYC'
# api_key_2 = 'E8J04H2JWSCENOKG'
# api_key_3 = '30B63PLFAA7F2C6K'
# api_key_4 = 'IL1S84LWPNAU5AZC'
# api_key_5 = 'FJUMLVR578JCX164'
# api_key_6 = 'LS3HW617Q3ZQ60U3'
# api_key_7 = 'M80WFUQ6UQP9MUOD'


# Define API keys for each sector
api_keys = {
    'Healthcare': 'M80WFUQ6UQP9MUOD',
    'Technology': 'E8J04H2JWSCENOKG',
    'Energy': '30B63PLFAA7F2C6K',
    'Consumer Staples': 'IL1S84LWPNAU5AZC',
    'Utilities': 'KA4LIC1TXIS8RKYC',
}

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=OVERVIEW&symbol=IBM&apikey=KA4LIC1TXIS8RKYC'
r = requests.get(url)
data = r.json()

print(data)

{'Symbol': 'IBM', 'AssetType': 'Common Stock', 'Name': 'International Business Machines', 'Description': 'International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcod

# Create Datasets

In [ ]:
companies = [
    # Healthcare Sector
    {'ticker': 'JNJ', 'name': 'Johnson & Johnson', 'sector': 'Healthcare'},
    {'ticker': 'UNH', 'name': 'UnitedHealth Group', 'sector': 'Healthcare'},
    {'ticker': 'PFE', 'name': 'Pfizer Inc.', 'sector': 'Healthcare'},
    {'ticker': 'MRK', 'name': 'Merck & Co.', 'sector': 'Healthcare'},
    {'ticker': 'ABBV', 'name': 'AbbVie Inc.', 'sector': 'Healthcare'},
    {'ticker': 'LLY', 'name': 'Eli Lilly and Co.', 'sector': 'Healthcare'},
    {'ticker': 'TMO', 'name': 'Thermo Fisher Scientific', 'sector': 'Healthcare'},
    {'ticker': 'ABT', 'name': 'Abbott Laboratories', 'sector': 'Healthcare'},
    {'ticker': 'BMY', 'name': 'Bristol-Myers Squibb', 'sector': 'Healthcare'},
    {'ticker': 'AMGN', 'name': 'Amgen Inc.', 'sector': 'Healthcare'},
    {'ticker': 'GILD', 'name': 'Gilead Sciences', 'sector': 'Healthcare'},
    {'ticker': 'NVO', 'name': 'Novo Nordisk', 'sector': 'Healthcare'},
    {'ticker': 'SNY', 'name': 'Sanofi-Aventis', 'sector': 'Healthcare'},
    {'ticker': 'VRTX', 'name': 'Vertex Pharmaceuticals', 'sector': 'Healthcare'},
    {'ticker': 'MDT', 'name': 'Medtronic PLC', 'sector': 'Healthcare'},

    # Technology Sector
    {'ticker': 'AAPL', 'name': 'Apple Inc.', 'sector': 'Technology'},
    {'ticker': 'MSFT', 'name': 'Microsoft Corporation', 'sector': 'Technology'},
    {'ticker': 'GOOGL', 'name': 'Alphabet Inc. (Class A)', 'sector': 'Technology'},
    {'ticker': 'GOOG', 'name': 'Alphabet Inc. (Class C)', 'sector': 'Technology'},
    {'ticker': 'AMZN', 'name': 'Amazon.com Inc.', 'sector': 'Technology'},
    {'ticker': 'META', 'name': 'Meta Platforms, Inc.', 'sector': 'Technology'},
    {'ticker': 'INTC', 'name': 'Intel Corporation', 'sector': 'Technology'},
    {'ticker': 'CSCO', 'name': 'Cisco Systems', 'sector': 'Technology'},
    {'ticker': 'NVDA', 'name': 'NVIDIA Corporation', 'sector': 'Technology'},
    {'ticker': 'ORCL', 'name': 'Oracle Corporation', 'sector': 'Technology'},
    {'ticker': 'ADBE', 'name': 'Adobe Inc.', 'sector': 'Technology'},
    {'ticker': 'CRM', 'name': 'Salesforce.com Inc.', 'sector': 'Technology'},
    {'ticker': 'IBM', 'name': 'IBM Corporation', 'sector': 'Technology'},
    {'ticker': 'TXN', 'name': 'Texas Instruments', 'sector': 'Technology'},
    {'ticker': 'AVGO', 'name': 'Broadcom Inc.', 'sector': 'Technology'},

    # Energy Sector
    {'ticker': 'XOM', 'name': 'Exxon Mobil Corporation', 'sector': 'Energy'},
    {'ticker': 'CVX', 'name': 'Chevron Corporation', 'sector': 'Energy'},
    {'ticker': 'COP', 'name': 'ConocoPhillips', 'sector': 'Energy'},
    {'ticker': 'SLB', 'name': 'Schlumberger Limited', 'sector': 'Energy'},
    {'ticker': 'EOG', 'name': 'EOG Resources', 'sector': 'Energy'},
    {'ticker': 'OXY', 'name': 'Occidental Petroleum', 'sector': 'Energy'},
    {'ticker': 'PSX', 'name': 'Phillips 66', 'sector': 'Energy'},
    {'ticker': 'MPC', 'name': 'Marathon Petroleum', 'sector': 'Energy'},
    {'ticker': 'VLO', 'name': 'Valero Energy', 'sector': 'Energy'},
    {'ticker': 'KMI', 'name': 'Kinder Morgan', 'sector': 'Energy'},
    {'ticker': 'HAL', 'name': 'Halliburton Company', 'sector': 'Energy'},
    {'ticker': 'DVN', 'name': 'Devon Energy', 'sector': 'Energy'},
    {'ticker': 'PXD', 'name': 'Pioneer Natural Resources', 'sector': 'Energy'},
    {'ticker': 'BKR', 'name': 'Baker Hughes', 'sector': 'Energy'},
    {'ticker': 'WMB', 'name': 'Williams Companies', 'sector': 'Energy'},

    # Consumer Staples Sector
    {'ticker': 'PG', 'name': 'Procter & Gamble', 'sector': 'Consumer Staples'},
    {'ticker': 'KO', 'name': 'Coca-Cola Company', 'sector': 'Consumer Staples'},
    {'ticker': 'PEP', 'name': 'PepsiCo Inc.', 'sector': 'Consumer Staples'},
    {'ticker': 'WMT', 'name': 'Walmart Inc.', 'sector': 'Consumer Staples'},
    {'ticker': 'COST', 'name': 'Costco Wholesale Corporation', 'sector': 'Consumer Staples'},
    {'ticker': 'PM', 'name': 'Philip Morris International', 'sector': 'Consumer Staples'},
    {'ticker': 'MO', 'name': 'Altria Group', 'sector': 'Consumer Staples'},
    {'ticker': 'MDLZ', 'name': 'Mondelez International', 'sector': 'Consumer Staples'},
    {'ticker': 'CL', 'name': 'Colgate-Palmolive', 'sector': 'Consumer Staples'},
    {'ticker': 'UL', 'name': 'Unilever PLC', 'sector': 'Consumer Staples'},
    {'ticker': 'KMB', 'name': 'Kimberly-Clark Corporation', 'sector': 'Consumer Staples'},
    {'ticker': 'GIS', 'name': 'General Mills', 'sector': 'Consumer Staples'},
    {'ticker': 'KHC', 'name': 'Kraft Heinz Company', 'sector': 'Consumer Staples'},
    {'ticker': 'EL', 'name': 'Estee Lauder Companies', 'sector': 'Consumer Staples'},
    {'ticker': 'TSN', 'name': 'Tyson Foods', 'sector': 'Consumer Staples'},

    # Utilities Sector
    {'ticker': 'NEE', 'name': 'NextEra Energy', 'sector': 'Utilities'},
    {'ticker': 'DUK', 'name': 'Duke Energy Corporation', 'sector': 'Utilities'},
    {'ticker': 'D', 'name': 'Dominion Energy', 'sector': 'Utilities'},
    {'ticker': 'SO', 'name': 'Southern Company', 'sector': 'Utilities'},
    {'ticker': 'AEP', 'name': 'American Electric Power', 'sector': 'Utilities'},
    {'ticker': 'EXC', 'name': 'Exelon Corporation', 'sector': 'Utilities'},
    {'ticker': 'SRE', 'name': 'Sempra Energy', 'sector': 'Utilities'},
    {'ticker': 'ED', 'name': 'Consolidated Edison', 'sector': 'Utilities'},
    {'ticker': 'PEG', 'name': 'Public Service Enterprise', 'sector': 'Utilities'},
    {'ticker': 'XEL', 'name': 'Xcel Energy', 'sector': 'Utilities'},
    {'ticker': 'PPL', 'name': 'PPL Corporation', 'sector': 'Utilities'},
    {'ticker': 'EIX', 'name': 'Edison International', 'sector': 'Utilities'},
    {'ticker': 'ETR', 'name': 'Entergy Corporation', 'sector': 'Utilities'},
    {'ticker': 'FE', 'name': 'FirstEnergy Corp.', 'sector': 'Utilities'},
    {'ticker': 'AEE', 'name': 'Ameren Corporation', 'sector': 'Utilities'}
]

In [ ]:
# Function to fetch historical data from Alpha Vantage
def fetch_stock_data(symbol, sector):
    """Fetches stock data using the appropriate API key for the sector."""
    api_key = api_keys.get(sector)  # Get API key for the sector
    if not api_key:
        print(f"No API key found for sector: {sector}")
        return pd.DataFrame()

    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&outputsize=full&apikey={api_key}'
    response = requests.get(url)
    data = response.json()

      # Check for error messages in the response
    if 'Error Message' in data:
        print(f"Error fetching data for {symbol}: {data['Error Message']}")
        return pd.DataFrame()
    elif 'Note' in data:
        print(f"Note for {symbol}: {data['Note']}") # This likely indicates rate limiting
        return pd.DataFrame()
    elif 'Time Series (Daily)' not in data:
        print(f"Unexpected response format for {symbol}: {data}")
        return pd.DataFrame()

    if 'Time Series (Daily)' in data:
        df = pd.DataFrame.from_dict(data['Time Series (Daily)'], orient='index')
        df.rename(columns={
            '1. open': 'Open',
            '2. high': 'High',
            '3. low': 'Low',
            '4. close': 'Close',
            '5. volume': 'Volume'
        }, inplace=True)
        df.index = pd.to_datetime(df.index)
        df = df[df.index >= '2020-07-01']
        df = df.apply(pd.to_numeric, errors='coerce')
        return df
    else:
        print(f"Failed to fetch data for {symbol}: {data.get('Note', 'Unknown error')}")
        return pd.DataFrame()

In [ ]:
# Compile all data into a single DataFrame
all_data = pd.DataFrame()

for company in companies:
    symbol = company['ticker']
    name = company['name']
    sector = company['sector']

    print(f"Fetching data for {name} ({symbol}) in sector: {sector}")
    stock_data = fetch_stock_data(symbol, sector)

    if not stock_data.empty:
        stock_data['Ticker'] = symbol
        stock_data['Company Name'] = name
        stock_data['Sector'] = sector
        all_data = pd.concat([all_data, stock_data])

    # 5/min so that we don't run out of API calls to AV
    sleep(12)

# Reset index and save to CSV
all_data.reset_index(inplace=True)
all_data.rename(columns={'index': 'Date'}, inplace=True)
all_data.to_csv('stock_data_with_sectors.csv', index=False)

print("Data collection complete. Saved to stock_data_with_sectors.csv")

Fetching data for Johnson & Johnson (JNJ) in sector: Healthcare
Fetching data for UnitedHealth Group (UNH) in sector: Healthcare
Fetching data for Pfizer Inc. (PFE) in sector: Healthcare
Fetching data for Merck & Co. (MRK) in sector: Healthcare
Fetching data for AbbVie Inc. (ABBV) in sector: Healthcare
Fetching data for Eli Lilly and Co. (LLY) in sector: Healthcare
Fetching data for Thermo Fisher Scientific (TMO) in sector: Healthcare
Fetching data for Abbott Laboratories (ABT) in sector: Healthcare
Fetching data for Bristol-Myers Squibb (BMY) in sector: Healthcare
Fetching data for Amgen Inc. (AMGN) in sector: Healthcare
Fetching data for Gilead Sciences (GILD) in sector: Healthcare
Fetching data for Novo Nordisk (NVO) in sector: Healthcare
Fetching data for Sanofi-Aventis (SNY) in sector: Healthcare
Fetching data for Vertex Pharmaceuticals (VRTX) in sector: Healthcare
Fetching data for Medtronic PLC (MDT) in sector: Healthcare
Fetching data for Apple Inc. (AAPL) in sector: Technology

In [ ]:
full_df = pd.read_csv('stock_data_with_sectors.csv')
# full_df.rename(columns={'5. volume': 'Volume'}, inplace=True)
full_df.head()

NameError: name 'pd' is not defined

In [ ]:
earliest_date = full_df['Date'].min()
print(earliest_date)

#post covid, when markets returned to normal

2020-07-01


In [ ]:
ts = TimeSeries(api_key, output_format='pandas')
data, meta = ts.get_daily('IBM')
data.head()



1. open   2. high    3. low  4. close  5. volume
date                                                        
2024-11-08   214.16  216.7000  212.7809    213.72  3201038.0
2024-11-07   213.64  214.5199  211.9300    213.69  3675812.0
2024-11-06   213.48  214.3300  210.3700    213.60  3934386.0
2024-11-05   206.17  208.1150  205.5700    207.57  2441535.0
2024-11-04   207.65  207.7000  205.8000    206.32  2594119.0

In [ ]:
earliest_date = data.last_valid_index()
print(earliest_date)

2024-06-20 00:00:00


In [ ]:
data_arr = data.to_numpy()
print("nump data array\n", data_arr)

nump data array
 [[2.1416000e+02 2.1670000e+02 2.1278090e+02 2.1372000e+02 3.1897530e+06]
 [2.1364000e+02 2.1451990e+02 2.1193000e+02 2.1369000e+02 3.6758120e+06]
 [2.1348000e+02 2.1433000e+02 2.1037000e+02 2.1360000e+02 3.9343860e+06]
 [2.0617000e+02 2.0811500e+02 2.0557000e+02 2.0757000e+02 2.4415350e+06]
 [2.0765000e+02 2.0770000e+02 2.0580000e+02 2.0632000e+02 2.5941190e+06]
 [2.0777000e+02 2.0984000e+02 2.0741000e+02 2.0825000e+02 3.3343080e+06]
 [2.0413000e+02 2.0813000e+02 2.0351000e+02 2.0672000e+02 5.9252500e+06]
 [2.0948000e+02 2.1112000e+02 2.0426000e+02 2.0490000e+02 6.9566240e+06]
 [2.1199000e+02 2.1334000e+02 2.0985000e+02 2.1043000e+02 5.2583660e+06]
 [2.1550000e+02 2.1625000e+02 2.1270000e+02 2.1291000e+02 4.9933430e+06]
 [2.1680000e+02 2.1865000e+02 2.1438500e+02 2.1467000e+02 8.4822350e+06]
 [2.2080000e+02 2.2132000e+02 2.1616000e+02 2.1839000e+02 1.1193440e+07]
 [2.3041000e+02 2.3334000e+02 2.3026000e+02 2.3275000e+02 5.7910020e+06]
 [2.3199000e+02 2.3297000e+02 2.30

In [ ]:
print(type(data_arr[0][0]))

<class 'numpy.float64'>
